title: "AIDA Data Hub"
description: "Data and services for AI innovation in medical imaging diagnostics."

theme: "jekyll-theme-cayman"
url: "https://datahub.aida.scilifelab.se"

collections:
  people:
    output: true
    layout: "person.html"
    permalink: "/preview/people/:path"
  datasets:
    output: true
    layout: "dataset.html"
    permalink: ":path"

defaults:
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "overhaul"
      description: "The people of AIDA Data Hub"
