title: "AIDA Data Hub"
description: "Data and services for AI innovation in medical imaging diagnostics."

theme: "jekyll-theme-cayman"
url: "https://datahub.aida.scilifelab.se"

collections:
  datasets:
    output: true
    layout: "dataset.html"
    permalink: ":path"

defaults:
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
