title: "AIDA Data Hub"
description: "Data and services for AI innovation in medical imaging diagnostics."

theme: "jekyll-theme-cayman"
url: "https://datahub.aida.scilifelab.se"

timezone: Europe/Stockholm
future: true

collections:
  datasets:
    output: true
    permalink: ":path"
  events:
    output: true
    permalink: "/preview/events/:path"
  news:
    output: true
    permalink: "/preview/news/:path"
  people:
    output: true
    permalink: "/preview/people/:path"

defaults:
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "overhaul"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "overhaul"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "overhaul"
      title: People
  - scope:
      path: "preview"
      type: "pages"
    values:
      layout: "overhaul"
