title: "AIDA Data Hub"
description: "Data and services for AI innovation in medical imaging diagnostics."

theme: "jekyll-theme-cayman"
url: "https://datahub.aida.scilifelab.se"

collections:
  datasets:
    output: true
    permalink: ":path"
  people:
    output: true
    permalink: "people/:path"

defaults:
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
