title: "AIDA Data Hub"
description: "Data and services for AI innovation in medical imaging diagnostics."

theme: "jekyll-theme-cayman"
url: "https://datahub.aida.scilifelab.se"

timezone: Europe/Stockholm
future: true

collections:
  datasets:
    output: true
    permalink: ":path"
  engagements:
    output: true
    permalink: "/about/engagements/:path/"
  events:
    output: true
    permalink: "/events/:path/"
  news:
    output: true
    permalink: "/news/:path/"
  people:
    output: true
    permalink: "/people/:path/"
  support-projects:
    output: true
    permalink: "/support/projects/:path/"
  training-events:
    output: true
    permaling: "/training/events/:path/"


defaults:
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
  - scope:
      path: ""
      type: "engagements"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "default"
      title: People
  - scope:
      path: ""
      type: "support-projects"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "training-events"
    values:
      layout: "default"
  - scope:
      path: "preview"
      type: "pages"
    values:
      layout: "default"
